### ISSUE TITLE
Fails to find mac address of hci0 with newer versions of bluez

### ISSUE THREAD

**Issue by GavinDarkglider** [pwnieexpress/blue_hydra#109]
It appears that the developers behind bluez have deprecated all hci* command line utilities, in favor of their new bluetoothctl tool. Unfortunately, this doesnt give many options to scripts like this that depend on those tools, as bluetoothctl is an interactive tool, that requires typing exit to exit.... Which mean that to get this to work with these new versions of bluez, the app is going to have to interact with dbus directly... :( 

Tested with bluez 5.46 in Gentoo Linux, using the blue_hydra-9999.ebuild from the pentoo repository.

**Comment by ZeroChaos-** [comment]
Fun, been expecting that. Will try to fix this week, thanks for the report!

**Comment by ZeroChaos-** [comment]
bluez didn't actually remove the needed utils, they just got more officially deprecated.  So for right now, I updated the ebuild with the proper deps.  This will be resolved a some point in the future for but now, it's fine to stick with these old tools in the minimal way they are used in blue_hydra
