### ISSUE TITLE
Is the --pulse option not working anymore?

### ISSUE THREAD

**Issue by gkt-aardvark** [pwnieexpress/blue_hydra#111]
I haven't used the --pulse (-p) option for a while and noticed now it's not working at all. It just throws an error.

Something along the lines of LOAD ERROR for the "require 'sensor_event'" part.

**Comment by ZeroChaos-** [comment]
Pwn Pulse is our cloud environment and the --pulse flag is meant to integrate into that for our paying customers.  Part of Pwn Pulse is a sensor feedback mechanism which is not shipped with blue_hydra (sensor_events).  We could easily make a flag for that, or just give you a new flag and document that --pulse is for PwnPulse customers only.  Do you have a preference?

**Comment by ZeroChaos-** [comment]
this should be fixed in the 1.9.8 tag (which will happen in an hour or so)
