### ISSUE TITLE
No detecting devices in non discoverable mode

### ISSUE THREAD

**Issue by rmoralesd** [pwnieexpress/blue_hydra#147]
Maybe this is a silly question or I misunderstood the blue hydra working principles. 
I have an odroid xu4 running Ubuntu 20.04.4 LTS kernel 5.4.191-242. I have successfully installed BlueHydra and all the stuff. I have an Ubertooth one and a USB bluetooth dongle. They are both detected:

Bus 003 Device 086: ID 1d50:6002 OpenMoko, Inc. Ubertooth One
Bus 003 Device 003: ID 0a5c:21e8 Broadcom Corp. BCM20702A0 Bluetooth 4.0

This is the issue. I have a Samsung Galaxy J7 prime, that I want to detect when it is nearby. If I run bluehydra and then I turn on the bluetooth of the phone, It is detected and shown as CL4.1 device.  But If I run bluehydra and I just don't make any interaction with the bluetooth of the phone, it is not detected ever.
¿am I misunderstanding how this works? ¿should the phone be detected?
Thanks.

**Comment by commodon** [comment]
I am not sure if I understand the steps you described in the second scenario, but in order for BlueHydra to detect devices with a Bluetooth interface in the local airspace, the Bluetooth interface on the device must be enabled, i.e. the Bluetooth interface must be on.

When the Bluetooth interface is enabled, it's operating in either of two states; discoverable or non-discoverable.

Discoverable is when the BT interface broadcasts its presence, making it highly visible to all other BT enabled devices in the immediate area. Often this might occur for a limited or fixed period of time, usually less than one or two minutes.  Generally this is NOT the default. This is an option/setting the user of the device may have to enable when initially pairing their device to another BT enabled device.

Non-discoverable is when the BT interface does not broadcast itself. Instead, it listens for the BT devices it has previously paired and assuming a previously paired device is detected, a connection is established.

Either way, discoverable or non-discoverable, the Bluetooth interface must be enabled for it to be detected.

**Comment by rmoralesd** [comment]
@commodon thanks for your detailed explanation. 
The Bluetooth interface of the phone is enabled, I can see the Bluetooth icon in the upper bar of the phone. Actually it lists the Bluetooth devices it has paired before, none of them is nearby so it does not try to connect, so I believe the Bluetooth's phone is in non-discoverable mode, just listening and not broadcasting. 

> If the BT interface is enabled regardless of which state it's in, discoverable or non-discoverable, BlueHydra should be able to detect its presence in the local airspace.

According to this, then my phone should be detected even in non-discoverable mode, but It does not. In order to be detected I have to "do something" with the Bluetooth, like trying to pair with any device of the list, or search for nearby devices, then Bluehydra sees it. ¿Do you have any idea what could be happening?

**Comment by commodon** [comment]
If the device has its BT interface enabled and if it's in a non-discoverable state, BlueHydra should be able to detect the device's presence it if you have the Ubertooth One adapter connected.

It's been a while since I've used BlueHydra, but if I remember correctly, it should indicate its use of the Ubertooth One adapter at the top of its output. When you're running BlueHydra does it reflect its detection and use of the Ubertooth One?

**Comment by ZeroChaos-** [comment]
If the bluetooth is enabled, but not in discoverable mode *and not in use* then it won't be detected as it won't be transmitting at all.  Blue_hydra does two things:
1.) Uses a standard bluetooth device to find classic devices in discoverable mode, and monitor btle advertisements (your phone won't be found by this as it's not in discoverable mode)
2.) Uses an ubertooth to sniff bluetooth classic communications, such as to a bluetooth headset.  When bluetooth is not in use, it doesn't transmit, and thus there is nothing for the ubertooth to sniff. (your phone won't be found this way either if it's not actively connected to some bluetooth device)

Honestly, I'm not sure what you are trying to do, but you could literally just use l2ping on your phone's mac address at a set interval to see if your phone is nearby.

**Comment by ZeroChaos-** [comment]
Blue_hydra does a last minute "save" of online devices which haven't been seen and are about to time out by using a targeted l2ping.  This is great for keeping found devices marked online when they don't leave or turn off. But it doesn't work if the device leaves or turns off and then comes back.

As for your detection question, it's not possible to detect a non-transmitting Bluetooth device, or really a non-transmitting anything.  Bluetooth low energy is surprisingly noisy, but Bluetooth classic is not.  If it's not in use but "turned on" then for most android phones that means it's dead silent.  iphones tend to leak btle which helps keep them visible, but they also use random Mac addresses while doing it which makes device identification difficult.

**Comment by rmoralesd** [comment]
@ZeroChaos- thanks a lot for clarifying this concepts. 
I will still working with BlueHydra, next step is extracting the data from sqlite database, perhaps I'll come back with some other issue ;). 
Thanks
