### ISSUE TITLE
 Unable to read the mac address from hci0

### ISSUE THREAD

**Issue by freeload101** [pwnieexpress/blue_hydra#57]
* I run it and it says "Unable to read the mac address from hci0"
* not sure what I should put in blue_hydra.yml for bt_device for ubertooth one
* kismit works with ubertooth
* patched to FW Firmware revision: 2015-10-R1
* ubertooth-specan-ui works fine
* ubertooth-dump looks ok I get rx block timestamp 2923969595 * 100 nanoseconds
* kismet works and can import to wireshark with ncsource=ubertooth and logtypes=......pcapbtbb in conf and plugin enabled in kismet
* python -V    " Python 2.7.6 "

* have bluez tools in $PATH

root@rmccurdyDOTcom:~/Downloads/blue_hydra/blue_hydra-develop/bin# blue
bluetooth-agent       bluetooth-sendto      bluez-simple-agent    bluez-test-adapter    bluez-test-device     bluez-test-input      bluez-test-network    bluez-test-service    
bluetoothd            bluetooth-wizard      bluez-simple-service  bluez-test-audio      bluez-test-discovery  bluez-test-manager    bluez-test-serial     bluez-test-telephony  

* have ubertooth tools in $PATH
root@rmccurdyDOTcom:~/Downloads/blue_hydra/blue_hydra-develop/bin# ubertooth-
ubertooth-btle       ubertooth-dfu        ubertooth-ego        ubertooth-rx         ubertooth-specan     ubertooth-util       
ubertooth-debug      ubertooth-dump       ubertooth-follow     ubertooth-scan       ubertooth-specan-ui  

* installed bluez-test-scripts to /usr/share/doc/bluez-test-scripts for blue_hydra-develop/bin/test-discovery

ot@rmccurdyDOTcom:~/Downloads/blue_hydra# ls /usr/share/doc/bluez-test-scripts/examples
bluezutils.py  list-devices       opp-client        service-did.xml  service-record.dtd  simple-endpoint.gz  test-alert.gz         test-discovery    test-heartrate  test-nap      test-proximity
dbusdef.py     map-client.gz      pbap-client.gz    service-ftp.xml  service-spp.xml     simple-player.gz    test-cyclingspeed.gz  test-health.gz    test-hfp.gz     test-network  test-sap-server
ftp-client.gz  monitor-bluetooth  sap_client.py.gz  service-opp.xml  simple-agent.gz     test-adapter        test-device.gz        test-health-sink  test-manager    test-profile  test-thermometer

# not sure what to put for ubertooth is it not hci0 ?
lsusb | grep Open
Bus 003 Device 010: ID 1d50:6002 OpenMoko, Inc.

**Comment by ZeroChaos-** [comment]
ubertooth is *not* a bluetooth adapter.  While ubertooth is supported, it is only supported in addition to a bluetooth adapter.  Please plug in a bluetooth adapter to use blue_hydra

**Comment by granolocks** [comment]
I'll update the readme to make this clearer.

**Comment by cloatre** [comment]
Hello,

I try your tool to check if my BLE bulb is detected and I have the same error:

---------------

root@kali:~/BLE/blue_hydra# bundle exec ./bin/blue_hydra
Unable to read the mac address from hci0


------------

Can the tool work with a hackRf? 
If not, with kind of cheap bluetooth adapter I have to buy?

Thanks,
