### ISSUE TITLE
ubertooth

### ISSUE THREAD

**Issue by genericnerd99** [pwnieexpress/blue_hydra#62]
Blue_Hydra is working great for me but could you comment on ubertooth operation please? i get "ubertooth status: not enabled"
Is there anything i have to do with jumpers, output to file, pipe etc? i'm running the 2015 firmware and ubertooth is working with other tools.  I've tried a lot but know im missing something obvious! running Ubuntu 16.04 on metal - better chances in Kali?

Any direction would be hugely grateful, loving the project thank you!

**Comment by ZeroChaos-** [comment]
this was probably fixed in https://github.com/pwnieexpress/blue_hydra/pull/63 which was just merged to develop.  please give it a try when you have a chance.  I'm closing this on the assumption that this is now fixed but if not, please feel free to reopen.

**Comment by genericnerd99** [comment]
sorry i'm still struggling, reinstalled hydra and ubertooth tried changing my locations, but no joy, is the best place to have ubertooth installed /usr/bin/ if i'm honest i haven't used my uber much as been waiting for a tool like hydra to come up, i am basic UT user.

Thanks again

**Comment by ZeroChaos-** [comment]
so how about now?

**Comment by genericnerd99** [comment]
i needed a full os wipe, reinstalled everything in /usr/local and its now working, i did use the latest version so could have been that, sorry i cant say for def but its now working perfectly thank you!
SmartTVs are so open and loud its scary. Again huge thanks!

**Comment by ZeroChaos-** [comment]
cool, well thanks for testing and confirming that things work.  hope you enjoy :-)
