### ISSUE TITLE
Blue Hydra Installation failing on Pwn Pad Community 

### ISSUE THREAD

**Issue by bibi1959** [pwnieexpress/blue_hydra#67]
I installed the community edition and is working great. Any effort to install blue_Hydra is negative. it seems it is actually impossible to install some pre-requisites packages like bluez-test-scripts. Pwn Pad is based on Kali moto and i do not know how to install all pre requistites as those packages are not available in kali "apgt-get install..."
Can you help?
Thanks
Bruno

**Comment by tmossey** [comment]
What hardware are you using?

**Comment by ZeroChaos-** [comment]
Pwn Pad 1 and 2 (as well as Pwn Phone) do not have a new enough kernel to run blue_hydra

Pwn Pad 3 and Pwn Pad 4 have it by default, but require a full upgrade to an AOPP based ROM

https://wiki.pwnieexpress.com/index.php/Installing_AOPP

**Comment by bibi1959** [comment]
I installed the communty editon on Nexus 7 16 Gb first Gen. Follwing your mail i guess i have to move to a Nexus 7 2013 device and install a new AOPP for the device. I iagine i can use any of the supported devices. Thanks 
Bruno

**Comment by ZeroChaos-** [comment]
The second Nexus 7 is also too old.  You need a nexus 9 or an nvidia shield if you want a new enough kernel to run blue_hydra

**Comment by ZeroChaos-** [comment]
and I specifically spelled out which devices you can and cannot use, so please see my comment above and stop imagining which devices are supported.
