### ISSUE TITLE
./bin/blue_hydra instant exit

### ISSUE THREAD

**Issue by schef** [pwnieexpress/blue_hydra#73]
Hi guys.
I have archlinux upToDate and Intel Corporation Wireless 3160 with bluetooth. I can scan and connect to BLE devices. So everything works.

But when i start the app with the command above i got instant exit after `press [Enter] key to continue....` message.
Any ideas?

**Comment by ZeroChaos-** [comment]
Check blue_hydra.log

**Comment by schef** [comment]
Here is my log.
http://pastebin.com/egbW71LP

**Comment by ZeroChaos-** [comment]
You need to run it as root

**Comment by schef** [comment]
Oh thanks.
