### ISSUE TITLE
Raspberry Pi 3 support

### ISSUE THREAD

**Issue by robotastic** [pwnieexpress/blue_hydra#77]
I want to get this running on the RPI 3's internal adaptor but it doesn't seem to be working.
HCI0 shows up when I run 'hciconfig'. I am using a stock install. When I launch bluehydra, it is not seeing any devices.
```
hci0:	Type: BR/EDR  Bus: UART
	BD Address: B8:27:EB:47:F4:7F  ACL MTU: 1021:8  SCO MTU: 64:1
	UP RUNNING 
	RX bytes:654 acl:0 sco:0 events:33 errors:0
	TX bytes:419 acl:0 sco:0 commands:33 errors:0
```

It does look like bluetoothd may have died, is that critical?

```
pi@raspberrypi:~ $ sudo /etc/init.d/bluetooth status
● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; disabled)
   Active: inactive (dead)
     Docs: man:bluetoothd(8)
pi@raspberrypi:~ $ 
```

**Comment by ZeroChaos-** [comment]
As mentioned on irc, check blue_hydra.log, but in short, yes that is critical.

At this time bluetoothd is required for discovery.

**Comment by ZeroChaos-** [comment]
Leaving this bug open as a reminder to:
1) improve documentation
2) improve erroring to cli when not in daemon mode

**Comment by E3V3A** [comment]
@robotastic 
I just tried this on a RPi3B (Jessie) and it seem to work just great. Was little tricky to get all dependencies clarified. Out of the box after bootup, you **don't** need to use `hciconfig` but rather check with:

```bash
$ hcitool dev
Devices:
        hci0    B8:27:EB:77:XX:XX
```

The right tool is to use `bluetoothctl` CLI and then type `show`, and exit with `quit`. 

The way to install is this:
```bash
sudo apt-get install -y bluez bluez-test-scripts python-bluez python-dbus
sudo apt-get install -y ruby-dev bundler
git clone https://github.com/pwnieexpress/blue_hydra.git
cd blue_hydra
bundle install
sudo ./bin/blue_hydra
```

@ZeroChaos- 
Please add this to your README.

**Comment by ZeroChaos-** [comment]
bundler is not *required*, but it's certainly helpful so I've added some comments on it's use.  thanks.
