### ISSUE TITLE
gem error for sqlite

### ISSUE THREAD

**Issue by Wiki61** [pwnieexpress/blue_hydra#78]
While building on Ubuntu 16.04 I ran into the error posted below. I solved the problem by also installing ruby-dev so that gem could install sqlite3.

Fetching gem metadata from http://rubygems.org/.........
Fetching version metadata from http://rubygems.org/..
Resolving dependencies...
Using rake 11.3.0
Using addressable 2.4.0
Using coderay 1.1.1
Using diff-lcs 1.2.5
Using louis 2.0.4
Using method_source 0.8.2
Using slop 3.6.0
Using rspec-support 3.5.0
Using bundler 1.11.2
Using data_objects 0.10.17
Using dm-core 1.2.1
Using pry 0.10.4
Using rspec-core 3.5.3
Using rspec-expectations 3.5.0
Using rspec-mocks 3.5.0
Installing do_sqlite3 0.10.17 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20160922-10636-h25cfmdo_sqlite3-0.10.17/gems/do_sqlite3-0.10.17/ext/do_sqlite3
/usr/bin/ruby2.3 -r ./siteconf20160922-10636-zxtsfk.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20160922-10636-h25cfmdo_sqlite3-0.10.17/gems/do_sqlite3-0.10.17 for inspection.
Results logged to /tmp/bundler20160922-10636-h25cfmdo_sqlite3-0.10.17/extensions/x86_64-linux/2.3.0/do_sqlite3-0.10.17/gem_make.out
Using dm-do-adapter 1.2.0
Using dm-migrations 1.2.0
Using dm-timestamps 1.2.0
Using dm-validations 1.2.0
Using rspec 3.5.0
An error occurred while installing do_sqlite3 (0.10.17), and Bundler cannot
continue.
Make sure that `gem install do_sqlite3 -v '0.10.17'` succeeds before bundling.

**Comment by bclune** [comment]
Can you install the `ruby-devel` package and see if that resolves the issue?

**Comment by Wiki61** [comment]
Yes that is how I solved the issue (ruby-dev). Sorry for submitting it as an issue since I fixed it, I just wanted to give a heads up.

**Comment by bclune** [comment]
No worries, it should be added to the readme.
