### ISSUE TITLE
Log Locations

### ISSUE THREAD

**Issue by fgranado** [pwnieexpress/blue_hydra#79]
This is more of a location question. So I see in /bin/blue_hydra.db is located but I was wondering if there is a way to view each individual hit from the bluetooth devices. I'm using http://sqlitebrowser.org/ to view the file and it only lets me see the initial and last packet, but how could I see each packet from a specific device? I don't know if there is a log saved somewhere else, thank you.

**Comment by granolocks** [comment]
Currently there isn't a way to see each time a device gets hit. In the `blue_hydra.yml` file you can set `btmon_log: true` and this will create a log of all the data we parse from `btmon` but you'll have to grep it manually for now. I dont think we plan to add this feature but you can certainly fork this repo and PR any changes :smile: 

In the Pwnie Express product called Pwn Pulse we periodically consume the data from blue hydra and create a historical timeline.

**Comment by ZeroChaos-** [comment]
This is *not* a sniffer. While we do use ubertooth's ability to sniff to aid in our device detection, we do not looj at the packet data at all (nor save it, etc). This tool is meant for device detection and basic sniffing, the ubertooth suite is for capturing data.
