### ISSUE TITLE
bluez 4.x requirement?

### ISSUE THREAD

**Issue by pcgeller** [pwnieexpress/blue_hydra#82]
Does blue hydra require bluez 4.x?

I have a rpi running debian 8 - jessie.  After meeting all the ruby and other system dependencies I was getting an error saying that bluez-utils cound't be found.  When I try to use apt-get I'm told that in jessie bluez 5 is used and the bluez-utils package is included in the bluez package.  I'm trying to backwards install v 4.99. 

What version of bluez was blue hydra built on?  Thanks in advance for the help!

**Comment by pcgeller** [comment]
Nm, got it working with bluez 5.23.   I'm trying to regenerate the error but I can't.

**Comment by ZeroChaos-** [comment]
We should update the docs to include the dep on bluez 5 instead of just bluez. Bluez 4 will not work, thanks for the poke on that.

**Comment by E3V3A** [comment]
I have these: 
```
ii  bluez                                 5.23-2+rpi2                               armhf        Bluetooth tools and daemons
ii  bluez-firmware                        1.2-3+rpi1                                all          Firmware for Bluetooth devices
ii  bluez-test-scripts                    5.23-2+rpi2                               all          BlueZ test scripts
ii  libbluetooth3:armhf                   5.23-2+rpi2                               armhf        Library to use the BlueZ Linux Bluetooth stack
ii  pi-bluetooth                          0.1.1                                     armhf        Raspberry Pi 3 bluetooth
ii  python-bluez                          0.20-1                                    armhf        Python wrappers around BlueZ for rapid blu tooth development
```
And it works great.

**Comment by ZeroChaos-** [comment]
added snarky comment about needing bluez 5 to the readme
