### ISSUE TITLE
Blue Hydra fails to continously run

### ISSUE THREAD

**Issue by krypton1c** [pwnieexpress/blue_hydra#91]
**Initial Setup:**

- Raspberry Pi Zero
- 2016-11-25-raspbian-jessie-lite
- Bus 001 Device 005: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n
- Bus 001 Device 004: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
- Bus 001 Device 003: ID 05e3:0608 Genesys Logic, Inc. USB-2.0 4-Port HUB
- Bus 001 Device 002: ID 05e3:0608 Genesys Logic, Inc. USB-2.0 4-Port HUB
- Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

After installing the OS, satisfying dependencies and executing blue_hydra as SUDO everything appears to be running fine however after roughly 3-5 minutes blue_hydra kills itself.

> Blue Hydra : Devices Seen in last 300s
Queue status: result_queue: 0, info_scan_queue: 1, l2ping_queue: 1
Discovery status timers: 46, ubertooth status: No hardware detected
 SEEN ^ | VERS  | ADDRESS           | RSSI | NAME        | MANUF | TYPE
   +18s | CL/BR | CC:6D:A0:__:__:__ | -71  | Roku Player | Roku  | Set-top box
Bluez reported hci0 not ready and failed to auto-reset with rfkill
Try removing and replugging the card, or toggling rfkill on and off

pi@raspberrypi:~/blue_hydra $ sudo rfkill list all
0: hci0: Bluetooth
        Soft blocked: no
        Hard blocked: no
1: phy0: Wireless LAN
        Soft blocked: no
        Hard blocked: no

Unplugging and replugging generally has no effect.  Then to make sure there was enough power I connected my WiFi (TPLink TL-WN722N) and Bluetooth (SENA UD100-G03) dongles on a powered USB hub.

Log Output:

I, [2017-01-09T00:39:49.319594 #1996]  INFO -- : BlueHydra Starting...
I, [2017-01-09T00:39:49.322038 #1996]  INFO -- : Runner starting with 'btmon -T -i hci0' ...
I, [2017-01-09T00:39:49.435431 #1996]  INFO -- : Marking older devices as 'offline'...
I, [2017-01-09T00:39:49.715138 #1996]  INFO -- : Btmon thread starting
I, [2017-01-09T00:39:49.717974 #1996]  INFO -- : Discovery thread starting
I, [2017-01-09T00:39:49.720624 #1996]  INFO -- : Chunker thread starting
I, [2017-01-09T00:39:49.723120 #1996]  INFO -- : Parser thread starting
I, [2017-01-09T00:39:49.792141 #1996]  INFO -- : Result thread starting
I, [2017-01-09T00:39:49.797191 #1996]  INFO -- : Command Line UI thread starting
E, [2017-01-09T00:40:35.466553 #1996] ERROR -- : Error with hciconfig hci0 reset..
E, [2017-01-09T00:40:35.468760 #1996] ERROR -- : Can't init device hci0: Connection timed out (110)
E, [2017-01-09T00:40:35.471556 #1996] ERROR -- : Bluez reported hci0 not ready, attempting to reset with rfkill
E, [2017-01-09T00:40:37.522937 #1996] ERROR -- : Bluez reported hci0 not ready and failed to reset with rfkill
I, [2017-01-09T00:40:37.527180 #1996]  INFO -- : Runner stopped. Exiting after clearing queue...
I, [2017-01-09T00:40:37.531515 #1996]  INFO -- : Queue clear! Exiting.
W, [2017-01-09T00:40:37.534530 #1996]  WARN -- : GOODBYE! ^_^

Installation Sources:

https://www.lazzaro.com.ar/Bluehydra-raspberrypi
https://www.linkedin.com/pulse/pwnie-express-blue-hydra-steven-perry

**Comment by ZeroChaos-** [comment]
the bluetooth dongle is dropping off the bus.  it either can't handle the load (I've toasted a few actually) or some other problem outside of blue hydra.  There is nothing we can do, the messages show that the bluetooth dongle stopped responding and we failed to recover it.

FWIW I've never blown a sena dongle up, and I hate the usb controller (or lack there of) on the rpi platform.

**Comment by krypton1c** [comment]
Is there a SBC platform that you have successfully run BH or recommendation?

**Comment by ZeroChaos-** [comment]
I've run bluehydra with great success on our Nexus 9 and Nvidia Shield android tablets, as well as a beagle bone black, all with a sena dongle.

**Comment by ZeroChaos-** [comment]
I'm also a big fan of Odroid hardware if you want something with a bit more power.
